# Generated by Django 5.0.1 on 2024-02-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0004_alter_document_chat"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="filepath",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
